[Этап 3] Финальное задание
GregSerbin/java-explore-with-me pull request #3
Opened 2024-10-17 14:37 UTC by GregSerbin

2024-10-18 06:07 UTC, VadimZharkov reviewed
В public EventFullDto findEventById(@PathVariable long userId,
                                      @PathVariable long eventId,
                                      HttpServletRequest request) throws InterruptedException 
InterruptedException  нигде не кидается, нужно убрать из определения метода

2024-10-18 06:11 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
Строки 161-193 и 376-408 содержат дублирующийся код. Лучше вынести в приватный метод.

2024-10-18 06:30 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/like/controller/LikeController.java
> +    public EventFullDto addLike(@PathVariable @Positive long eventId,
Необходимо добавить `@Validated `в контроллер на уровне класса, чтобы проверять переменные пути аннотациями типа `@Positive, @Min, @Maх` и т.д.

2024-10-18 06:36 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/like/service/LikeServiceImpl.java
> +        Optional<Like> likeOptional = likeRepository.findByEventAndUser(event, user);
Здесь тоже можно было 
.orElseThrow(() -> new RestrictionsViolationException("Вы еще не оценивали событие");
а дальше 
StatusLike statusLike = like.getStatus();
likeRepository.delete(like);
changeRatingUserAndEvent(event, statusLike, DIFFERENCE_RATING_BY_DELETE);

Меньше if else и отступов, короче и проще код

2024-10-18 06:40 UTC, VadimZharkov requested changes
Хорошая работа, можно улучшить

2024-10-18 07:21 UTC, GregSerbin commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
В этих строках проверки одинаковые, но для 2-х разных DTO.  В строках 161-193 для пользователя (UpdateEventUserRequest), в строках 376-408 для админа (UpdateEventAdminRequest). 

Не очень понимаю, как сделать 1 метод для проверки разных типов. 
Думал в сторону выделения полей в родительский класс, но это, судя по постам в интернете, плохая практика. 
Или можно с помощью Lombok выделить общий интерфейс?

Подскажи, в какую сторону копать?

2024-10-20 05:58 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
можно вынести в метод общий код после получения Event из репозитория
например сделать такой метод
`private void updateEvent(Event event, String annotation, Long categoryId, String description, LocalDateTime eventDate, Location location, Boolean paid, Long participantLimit, Boolean requestModeration, String title) 
`
и затем его вызывать
```
       Event event = eventRepository.findById(eventId)
                .orElseThrow(() -> new NotFoundException(String.format("Событие с id=%d не существует", eventId)));

        updateEvent(event, updateEvent.getAnnotation(), updateEvent.getCategory(), updateEvent.getDescription(), updateEvent.getEventDate(), updateEvent.getLocation(), updateEvent.getPaid(), updateEvent.getParticipantLimit(), updateEvent.getRequestModeration(), updateEvent.getTitle());
```
это по простому.

можно также для этих Dto сделать базовый интерфейс UpdateEventRequest с методами 
getAnnotation(), getCategory() и т.д.
и тогда updateEvent(event, updateEventRequest) будет выглядеть поприятней)

2024-10-20 06:01 UTC, VadimZharkov requested changes
В части общего кода можно улучшить

2024-10-20 10:21 UTC, GregSerbin commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
Исправил

2024-10-20 11:08 UTC, VadimZharkov approved these changes

2024-10-20 13:50 UTC, merged